/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HoursRouteImport } from './routes/hours'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TradeInRouteImport } from './routes/trade-in'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as FinancingIndexRouteImport } from './routes/financing/index'
import { Route as FinancingPrequalifyRouteImport } from './routes/financing/prequalify'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as InventorySlugRouteImport } from './routes/inventory/$slug'
import { Route as InventoryNewRouteImport } from './routes/inventory/new'
import { Route as InventoryUsedRouteImport } from './routes/inventory/used'
import { Route as PartsIndexRouteImport } from './routes/parts/index'
import { Route as PartsRequestRouteImport } from './routes/parts/request'
import { Route as ReviewsIndexRouteImport } from './routes/reviews/index'
import { Route as ReviewsSubmitRouteImport } from './routes/reviews/submit'
import { Route as ServiceIndexRouteImport } from './routes/service/index'
import { Route as ServiceAppointmentsRouteImport } from './routes/service/appointments'
import { Route as ServiceCeramicRouteImport } from './routes/service/ceramic'
import { Route as ServiceDetailingRouteImport } from './routes/service/detailing'
import { Route as ServiceStorageRouteImport } from './routes/service/storage'
import { Route as AdminBlogsIndexRouteImport } from './routes/admin/blogs/index'
import { Route as AdminBlogsIdRouteImport } from './routes/admin/blogs/$id'
import { Route as AdminListingsIndexRouteImport } from './routes/admin/listings/index'
import { Route as AdminListingsIdRouteImport } from './routes/admin/listings/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HoursRoute = HoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeInRoute = TradeInRouteImport.update({
  id: '/trade-in',
  path: '/trade-in',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingIndexRoute = FinancingIndexRouteImport.update({
  id: '/financing/',
  path: '/financing/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingPrequalifyRoute = FinancingPrequalifyRouteImport.update({
  id: '/financing/prequalify',
  path: '/financing/prequalify',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorySlugRoute = InventorySlugRouteImport.update({
  id: '/inventory/$slug',
  path: '/inventory/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryNewRoute = InventoryNewRouteImport.update({
  id: '/inventory/new',
  path: '/inventory/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryUsedRoute = InventoryUsedRouteImport.update({
  id: '/inventory/used',
  path: '/inventory/used',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsIndexRoute = PartsIndexRouteImport.update({
  id: '/parts/',
  path: '/parts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRequestRoute = PartsRequestRouteImport.update({
  id: '/parts/request',
  path: '/parts/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsSubmitRoute = ReviewsSubmitRouteImport.update({
  id: '/reviews/submit',
  path: '/reviews/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceIndexRoute = ServiceIndexRouteImport.update({
  id: '/service/',
  path: '/service/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAppointmentsRoute = ServiceAppointmentsRouteImport.update({
  id: '/service/appointments',
  path: '/service/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceCeramicRoute = ServiceCeramicRouteImport.update({
  id: '/service/ceramic',
  path: '/service/ceramic',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceDetailingRoute = ServiceDetailingRouteImport.update({
  id: '/service/detailing',
  path: '/service/detailing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceStorageRoute = ServiceStorageRouteImport.update({
  id: '/service/storage',
  path: '/service/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogsIndexRoute = AdminBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsIdRoute = AdminBlogsIdRouteImport.update({
  id: '/blogs/$id',
  path: '/blogs/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsIndexRoute = AdminListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsIdRoute = AdminListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/favorites': typeof FavoritesRoute
  '/hours': typeof HoursRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/policy': typeof PolicyRoute
  '/privacy': typeof PrivacyRoute
  '/promotions': typeof PromotionsRoute
  '/quote': typeof QuoteRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/trade-in': typeof TradeInRoute
  '/warranty': typeof WarrantyRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/financing/prequalify': typeof FinancingPrequalifyRoute
  '/inventory/$slug': typeof InventorySlugRoute
  '/inventory/new': typeof InventoryNewRoute
  '/inventory/used': typeof InventoryUsedRoute
  '/parts/request': typeof PartsRequestRoute
  '/reviews/submit': typeof ReviewsSubmitRoute
  '/service/appointments': typeof ServiceAppointmentsRoute
  '/service/ceramic': typeof ServiceCeramicRoute
  '/service/detailing': typeof ServiceDetailingRoute
  '/service/storage': typeof ServiceStorageRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/financing/': typeof FinancingIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/parts/': typeof PartsIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/admin/blogs/$id': typeof AdminBlogsIdRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/careers': typeof CareersRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/favorites': typeof FavoritesRoute
  '/hours': typeof HoursRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/policy': typeof PolicyRoute
  '/privacy': typeof PrivacyRoute
  '/promotions': typeof PromotionsRoute
  '/quote': typeof QuoteRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/trade-in': typeof TradeInRoute
  '/warranty': typeof WarrantyRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/financing/prequalify': typeof FinancingPrequalifyRoute
  '/inventory/$slug': typeof InventorySlugRoute
  '/inventory/new': typeof InventoryNewRoute
  '/inventory/used': typeof InventoryUsedRoute
  '/parts/request': typeof PartsRequestRoute
  '/reviews/submit': typeof ReviewsSubmitRoute
  '/service/appointments': typeof ServiceAppointmentsRoute
  '/service/ceramic': typeof ServiceCeramicRoute
  '/service/detailing': typeof ServiceDetailingRoute
  '/service/storage': typeof ServiceStorageRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/financing': typeof FinancingIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/parts': typeof PartsIndexRoute
  '/reviews': typeof ReviewsIndexRoute
  '/service': typeof ServiceIndexRoute
  '/admin/blogs/$id': typeof AdminBlogsIdRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
  '/admin/listings': typeof AdminListingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/favorites': typeof FavoritesRoute
  '/hours': typeof HoursRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/policy': typeof PolicyRoute
  '/privacy': typeof PrivacyRoute
  '/promotions': typeof PromotionsRoute
  '/quote': typeof QuoteRoute
  '/schedule': typeof ScheduleRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/trade-in': typeof TradeInRoute
  '/warranty': typeof WarrantyRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/financing/prequalify': typeof FinancingPrequalifyRoute
  '/inventory/$slug': typeof InventorySlugRoute
  '/inventory/new': typeof InventoryNewRoute
  '/inventory/used': typeof InventoryUsedRoute
  '/parts/request': typeof PartsRequestRoute
  '/reviews/submit': typeof ReviewsSubmitRoute
  '/service/appointments': typeof ServiceAppointmentsRoute
  '/service/ceramic': typeof ServiceCeramicRoute
  '/service/detailing': typeof ServiceDetailingRoute
  '/service/storage': typeof ServiceStorageRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/financing/': typeof FinancingIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/parts/': typeof PartsIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/admin/blogs/$id': typeof AdminBlogsIdRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/careers'
    | '/compare'
    | '/contact'
    | '/events'
    | '/favorites'
    | '/hours'
    | '/login'
    | '/newsletter'
    | '/policy'
    | '/privacy'
    | '/promotions'
    | '/quote'
    | '/schedule'
    | '/sitemap'
    | '/terms'
    | '/trade-in'
    | '/warranty'
    | '/admin/leads'
    | '/admin/staff'
    | '/blog/$slug'
    | '/financing/prequalify'
    | '/inventory/$slug'
    | '/inventory/new'
    | '/inventory/used'
    | '/parts/request'
    | '/reviews/submit'
    | '/service/appointments'
    | '/service/ceramic'
    | '/service/detailing'
    | '/service/storage'
    | '/admin/'
    | '/blog/'
    | '/financing/'
    | '/inventory/'
    | '/parts/'
    | '/reviews/'
    | '/service/'
    | '/admin/blogs/$id'
    | '/admin/listings/$id'
    | '/api/auth/$'
    | '/admin/blogs/'
    | '/admin/listings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/careers'
    | '/compare'
    | '/contact'
    | '/events'
    | '/favorites'
    | '/hours'
    | '/login'
    | '/newsletter'
    | '/policy'
    | '/privacy'
    | '/promotions'
    | '/quote'
    | '/schedule'
    | '/sitemap'
    | '/terms'
    | '/trade-in'
    | '/warranty'
    | '/admin/leads'
    | '/admin/staff'
    | '/blog/$slug'
    | '/financing/prequalify'
    | '/inventory/$slug'
    | '/inventory/new'
    | '/inventory/used'
    | '/parts/request'
    | '/reviews/submit'
    | '/service/appointments'
    | '/service/ceramic'
    | '/service/detailing'
    | '/service/storage'
    | '/admin'
    | '/blog'
    | '/financing'
    | '/inventory'
    | '/parts'
    | '/reviews'
    | '/service'
    | '/admin/blogs/$id'
    | '/admin/listings/$id'
    | '/api/auth/$'
    | '/admin/blogs'
    | '/admin/listings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/careers'
    | '/compare'
    | '/contact'
    | '/events'
    | '/favorites'
    | '/hours'
    | '/login'
    | '/newsletter'
    | '/policy'
    | '/privacy'
    | '/promotions'
    | '/quote'
    | '/schedule'
    | '/sitemap'
    | '/terms'
    | '/trade-in'
    | '/warranty'
    | '/admin/leads'
    | '/admin/staff'
    | '/blog/$slug'
    | '/financing/prequalify'
    | '/inventory/$slug'
    | '/inventory/new'
    | '/inventory/used'
    | '/parts/request'
    | '/reviews/submit'
    | '/service/appointments'
    | '/service/ceramic'
    | '/service/detailing'
    | '/service/storage'
    | '/admin/'
    | '/blog/'
    | '/financing/'
    | '/inventory/'
    | '/parts/'
    | '/reviews/'
    | '/service/'
    | '/admin/blogs/$id'
    | '/admin/listings/$id'
    | '/api/auth/$'
    | '/admin/blogs/'
    | '/admin/listings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRouteWithChildren
  CareersRoute: typeof CareersRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FavoritesRoute: typeof FavoritesRoute
  HoursRoute: typeof HoursRoute
  LoginRoute: typeof LoginRoute
  NewsletterRoute: typeof NewsletterRoute
  PolicyRoute: typeof PolicyRoute
  PrivacyRoute: typeof PrivacyRoute
  PromotionsRoute: typeof PromotionsRoute
  QuoteRoute: typeof QuoteRoute
  ScheduleRoute: typeof ScheduleRoute
  SitemapRoute: typeof SitemapRoute
  TermsRoute: typeof TermsRoute
  TradeInRoute: typeof TradeInRoute
  WarrantyRoute: typeof WarrantyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  FinancingPrequalifyRoute: typeof FinancingPrequalifyRoute
  InventorySlugRoute: typeof InventorySlugRoute
  InventoryNewRoute: typeof InventoryNewRoute
  InventoryUsedRoute: typeof InventoryUsedRoute
  PartsRequestRoute: typeof PartsRequestRoute
  ReviewsSubmitRoute: typeof ReviewsSubmitRoute
  ServiceAppointmentsRoute: typeof ServiceAppointmentsRoute
  ServiceCeramicRoute: typeof ServiceCeramicRoute
  ServiceDetailingRoute: typeof ServiceDetailingRoute
  ServiceStorageRoute: typeof ServiceStorageRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FinancingIndexRoute: typeof FinancingIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  PartsIndexRoute: typeof PartsIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  ServiceIndexRoute: typeof ServiceIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hours': {
      id: '/hours'
      path: '/hours'
      fullPath: '/hours'
      preLoaderRoute: typeof HoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-in': {
      id: '/trade-in'
      path: '/trade-in'
      fullPath: '/trade-in'
      preLoaderRoute: typeof TradeInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing/': {
      id: '/financing/'
      path: '/financing'
      fullPath: '/financing/'
      preLoaderRoute: typeof FinancingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing/prequalify': {
      id: '/financing/prequalify'
      path: '/financing/prequalify'
      fullPath: '/financing/prequalify'
      preLoaderRoute: typeof FinancingPrequalifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$slug': {
      id: '/inventory/$slug'
      path: '/inventory/$slug'
      fullPath: '/inventory/$slug'
      preLoaderRoute: typeof InventorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/new': {
      id: '/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof InventoryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/used': {
      id: '/inventory/used'
      path: '/inventory/used'
      fullPath: '/inventory/used'
      preLoaderRoute: typeof InventoryUsedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/': {
      id: '/parts/'
      path: '/parts'
      fullPath: '/parts/'
      preLoaderRoute: typeof PartsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/request': {
      id: '/parts/request'
      path: '/parts/request'
      fullPath: '/parts/request'
      preLoaderRoute: typeof PartsRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/submit': {
      id: '/reviews/submit'
      path: '/reviews/submit'
      fullPath: '/reviews/submit'
      preLoaderRoute: typeof ReviewsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/': {
      id: '/service/'
      path: '/service'
      fullPath: '/service/'
      preLoaderRoute: typeof ServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/appointments': {
      id: '/service/appointments'
      path: '/service/appointments'
      fullPath: '/service/appointments'
      preLoaderRoute: typeof ServiceAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/ceramic': {
      id: '/service/ceramic'
      path: '/service/ceramic'
      fullPath: '/service/ceramic'
      preLoaderRoute: typeof ServiceCeramicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/detailing': {
      id: '/service/detailing'
      path: '/service/detailing'
      fullPath: '/service/detailing'
      preLoaderRoute: typeof ServiceDetailingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/storage': {
      id: '/service/storage'
      path: '/service/storage'
      fullPath: '/service/storage'
      preLoaderRoute: typeof ServiceStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blogs/': {
      id: '/admin/blogs/'
      path: '/blogs'
      fullPath: '/admin/blogs/'
      preLoaderRoute: typeof AdminBlogsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/$id': {
      id: '/admin/blogs/$id'
      path: '/blogs/$id'
      fullPath: '/admin/blogs/$id'
      preLoaderRoute: typeof AdminBlogsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/': {
      id: '/admin/listings/'
      path: '/listings'
      fullPath: '/admin/listings/'
      preLoaderRoute: typeof AdminListingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/$id': {
      id: '/admin/listings/$id'
      path: '/listings/$id'
      fullPath: '/admin/listings/$id'
      preLoaderRoute: typeof AdminListingsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogsIdRoute: typeof AdminBlogsIdRoute
  AdminListingsIdRoute: typeof AdminListingsIdRoute
  AdminBlogsIndexRoute: typeof AdminBlogsIndexRoute
  AdminListingsIndexRoute: typeof AdminListingsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLeadsRoute: AdminLeadsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogsIdRoute: AdminBlogsIdRoute,
  AdminListingsIdRoute: AdminListingsIdRoute,
  AdminBlogsIndexRoute: AdminBlogsIndexRoute,
  AdminListingsIndexRoute: AdminListingsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRouteWithChildren,
  CareersRoute: CareersRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FavoritesRoute: FavoritesRoute,
  HoursRoute: HoursRoute,
  LoginRoute: LoginRoute,
  NewsletterRoute: NewsletterRoute,
  PolicyRoute: PolicyRoute,
  PrivacyRoute: PrivacyRoute,
  PromotionsRoute: PromotionsRoute,
  QuoteRoute: QuoteRoute,
  ScheduleRoute: ScheduleRoute,
  SitemapRoute: SitemapRoute,
  TermsRoute: TermsRoute,
  TradeInRoute: TradeInRoute,
  WarrantyRoute: WarrantyRoute,
  BlogSlugRoute: BlogSlugRoute,
  FinancingPrequalifyRoute: FinancingPrequalifyRoute,
  InventorySlugRoute: InventorySlugRoute,
  InventoryNewRoute: InventoryNewRoute,
  InventoryUsedRoute: InventoryUsedRoute,
  PartsRequestRoute: PartsRequestRoute,
  ReviewsSubmitRoute: ReviewsSubmitRoute,
  ServiceAppointmentsRoute: ServiceAppointmentsRoute,
  ServiceCeramicRoute: ServiceCeramicRoute,
  ServiceDetailingRoute: ServiceDetailingRoute,
  ServiceStorageRoute: ServiceStorageRoute,
  BlogIndexRoute: BlogIndexRoute,
  FinancingIndexRoute: FinancingIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  PartsIndexRoute: PartsIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  ServiceIndexRoute: ServiceIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
